whi_3dobject_tracking:
  view_color: true
  view_depth: true
  visualize_pose_result: false
  use_region_modality: true
  use_depth_modality: true
  use_texture_modality: false
  measure_occlusions: false
  model_occlusions: false
  tracking_on_start: false
  bodies: ["io_485"] #[ "io_485", "triangle" ]
  directory: /home/whi/catkin_workspace/src/whi_3dobject_tracking/data
  color_topic: color_view
  color_overlay_topic: color_overlay_view
  depth_topic: depth_view
  depth_overlay_topic: depth_overlay_view
  pose_topic: tcp_pose
  pose_service: tcp_pose
  pose_frame: camera
  # chin: [0, 0, 0, -1.5708, 0, -1.5708] and [0.18, 0, 0]
  # world_to_tcp: [0, 0, 0, -1.5708, 0, -1.5708]
  # object_to_tcp: [0, 0, 0, 0, -1.5708, 0]
  # position_reference: [0.18, 0, 0]
  # ur: [0, 0, 0, 1.5708, 0, 0] and [0, -0.18, 0]
  world_to_tcp: [0, 0, 0, 1.5708, 0, 0]
  object_to_tcp: [0, 0, 0, 1.5708, -1.5708, 0]
  position_reference: [0, -0.18, 0]
  euler_muliplier: [0.0, 0.0, 0.0]
