whi_3dobject_tracking:
  view_color: true
  view_depth: true
  visualize_pose_result: true
  use_region_modality: true
  use_depth_modality: true
  use_texture_modality: false
  measure_occlusions: false
  model_occlusions: false
  tracking_on_start: false
  bodies: ["io_485"] #[ "io_485", "triangle" ]
  directory: /home/whi/catkin_workspace/src/whi_3dobject_tracking/data
  color_topic: color_view
  depth_topic: depth_view
  pose_topic: /tcp_pose
  pose_frame: camera
  # transform_to_tcp: [0, 0, 0, 1.5708, 0, 0]
